version: '3'

networks:
    laravel:
        driver: bridge

services:
    app:
        build: .
        ports:
            - "8000:80"
        volumes:
            - .:/usr/share/nginx
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel
        container_name: app-container
    mariadb:
        image: mariadb
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_NAME: mariadb
        networks:
            - laravel
        volumes:
            - ./.docker/dbdata:/var/lib/mysql
        container_name: mariadb-container

