version: '3'

services:
    mariadb:
        image: mariadb
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
            - .:/var/www/ingressoteca/storage/app
        ports:
            - 3306:3306
    app:
        build: .
        command: php artisan serve --host=0.0.0.0
        volumes:
            - .:/var/www/ingressoteca
